# Website settings
baseurl: "/portfolio"
url: "http://www.hunglethanh9.github.io"

# Internal nav
nav:
  main:
    writing: "/writing"
    speaking: "/speaking"
    projects: "/projects"
    photos: "/photos"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Hung Le Thanh"
description: "The home page of Hung Le Thanh, Technical Evangelist at Google Developer Group Hanoi"
# thumbnail_path: "hungle.jpg"
# bitcoin_address: "1G8qEUVUS8BBSwSWNM4EWR622vUpGtee66"
hello_startup_url: "http://www.hello-startup.net/"
website_repo_url: "https://github.com/hungle90"
# atomic_squirrel_url: "http://www.atomic-squirrel.net/"
# gruntwork_url: "http://www.gruntwork.io/"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/hunglt9"
    label: "Twitter"
    icon: "twitter-square"
    username: "@brikis98"
  linkedin:
    url: "https://www.linkedin.com/in/hunglethanh"
    label: "LinkedIn"
    icon: "linkedin-square"
  facebook:
    url: "https://www.facebook.com/hunglt90"
    label: "Facebook"
    icon: "facebook-square"
  google:
    url: "https://plus.google.com/+HungLeThanh/"
    label: "Google+"
    icon: "google-plus-square"
  slideshare:
    url: "http://www.slideshare.net/HungLeThanh1"
    label: "SlideShare"
    icon: "slideshare"
  github:
    url: "https://github.com/hungle90/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:lehung229@gmail.com"
    label: "Email"
    value: "lehung229@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
